name: mindpeers_intro
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  bloc_concurrency: ^0.2.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_spinkit: ^5.1.0
  flutter_svg: ^1.1.5
  freezed_annotation: ^2.1.0
  get_it: ^7.2.0
  http: ^0.13.5
  injectable: ^1.5.3
  rxdart: ^0.27.5
  sizer: ^2.0.15

dev_dependencies:
  build_runner: ^2.3.2
  flutter_test:
    sdk: flutter
  freezed: ^2.2.0
  injectable_generator: ^1.5.4
  json_serializable: ^6.3.2
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/json/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
